[package]
name = "wgpu-remote"
version = "0.1.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
edition = "2018"

[features]
default = []

[dependencies]
wgpu-native = { path = "../wgpu-native", features = ["remote"] }
ipc-channel = "0.11"
log = "0.4"
parking_lot = { version = "0.7" }
serde = { version = "1.0", features = ["serde_derive"] }
