language: rust
sudo: false
dist: xenial

matrix:
  include:
    # Linux 64bit
    - os: linux
      rust: stable
      compiler: gcc
    #TODO: unlock when libglfw3 on Ubuntu comes with Vulkan support
    # or when we add a GL backend.
    #- os: linux
    #  rust: nightly
    #  compiler: gcc
    # Windows 64bit
    - os: windows
      rust: stable

    # macOS 64bit
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      rust: stable
      osx_image: xcode9.4
      compiler: clang
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      rust: nightly
      osx_image: xcode9.4
      compiler: clang

    # iPhoneOS 64bit
    #- env: TARGET=aarch64-apple-ios
    #  os: osx
    #  osx_image: xcode9.4
    #  rust: nightly

addons:
  apt:
    packages:
    - cmake
    - libglfw3-dev
  homebrew:
    update: true
    packages:
    - cmake
    - glfw3
  choco:
    packages:
    - make

branches:
  except:
  - staging.tmp

before_install:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install make; fi

script:
  - cargo test
  - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo +nightly install cbindgen && make VERBOSE=1; fi
