[package]
name = "wgpu-bindings"
version = "0.1.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
edition = "2018"

[features]
default = []

[dependencies]
cbindgen = { git = "https://github.com/eqrion/cbindgen", rev = "2932819" }
