[package]
name = "wgpu"
version = "0.1.0"
authors = [
	"Dzmitry Malyshau <kvark@mozilla.com>",
	"Joshua Groves <josh@joshgroves.com>",
]
edition = "2018"

[lib]

[features]
default = []
backed = []
metal = ["wgpu-native/gfx-backend-metal", "backed"]
dx12 = ["wgpu-native/gfx-backend-dx12", "backed"]
vulkan = ["wgpu-native/gfx-backend-vulkan", "backed"]

[dependencies]
wgpu-native = { path = "../wgpu-native" }
arrayvec = "0.4"
