[package]
name = "wgpu-info"
version = "0.9.0"
authors = ["wgpu developers"]
edition = "2018"
description = "Adapter information and per-adapter test program"
homepage = "https://github.com/gfx-rs/wgpu"
repository = "https://github.com/gfx-rs/wgpu"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[dependencies]
wgpu = { version = "0.9", path = "../wgpu" }
