[package]
name = "wgpu-hal"
version = "0.1.0"
authors = ["wgpu developers"]
edition = "2018"
description = "WebGPU hardware abstraction layer"
homepage = "https://github.com/gfx-rs/wgpu"
repository = "https://github.com/gfx-rs/wgpu"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[lib]

[features]
metal = ["mtl"]

[dependencies]
bitflags = "1.0"
raw-window-handle = "0.3"
smallvec = "1"
thiserror = "1"
wgt = { package = "wgpu-types", path = "../wgpu-types" }

# backends
mtl = { package = "metal", version = "0.22", optional = true }

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-25"

[dev-dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-25"
features = ["wgsl-in"]

[dev-dependencies]
winit = "0.24"
