[package]
name = "wgpu-hal"
version = "0.1.0"
authors = ["wgpu developers"]
edition = "2018"
description = "WebGPU hardware abstraction layer"
homepage = "https://github.com/gfx-rs/wgpu"
repository = "https://github.com/gfx-rs/wgpu"
keywords = ["graphics"]
license = "MIT OR Apache-2.0"

[lib]

[features]
default = ["metal"]
metal = ["foreign-types", "mtl", "objc", "parking_lot", "naga/msl-out"]

[dependencies]
arrayvec = "0.5"
bitflags = "1.0"
fxhash = "0.2"
log = "0.4"
parking_lot = { version = "0.11", optional = true }
raw-window-handle = "0.3"
thiserror = "1"
wgt = { package = "wgpu-types", path = "../wgpu-types" }

# backends
foreign-types = { version = "0.3", optional = true }
mtl = { package = "metal", version = "0.22", optional = true }
objc = { version = "0.2.5", optional = true }

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-25"

[dev-dependencies.naga]
git = "https://github.com/gfx-rs/naga"
tag = "gfx-25"
features = ["wgsl-in"]

[dev-dependencies]
winit = "0.24"
